apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: caddy-test
  namespace: caddy
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/caddy-repo.git
    targetRevision:  changes
    path: caddy
  destination:
    server: https://kubernetes.default.svc
    namespace: caddy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
