apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
        - image: caddy:latest
          name: caddy-test
          ports:
            - containerPort: 8801
